export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const VERIFY_TOKEN="VERIFY_TOKEN";
export const PROFILE_DATA="PROFILE_DATA";